sudo: required

services:
  - docker

before_install:
  - docker --version

install:

script:
  - docker build --pull --tag ghusta/postgres-world-db .
  - docker inspect --format="{{json .Config.Healthcheck}}" ghusta/postgres-world-db

after_success:
  - docker image ls
